### ISSUE TITLE
something for the test mask

### ISSUE THREAD

**Issue by Liumomo30** [wooseok-shin/PrevMatch#1]
Hello, thank you for your contribution to the code, how should I predict the test set to generate the test mask map, is there any code for that？thanks for the reply！

**Comment by wooseok-shin** [comment]
Hi, thank you for your interest in our research.

I have updated evaluate.py and evaluate.sh. 
And I have updated it to save both the actual mask (consisting of class numbers) and the color mask.
If you want to save the prediction map, you can add **True** as below.

sh scripts/evaluate.sh pascal trained_weights/pascal_92_73.7.pth **True**

**Comment by Liumomo30** [comment]
Thanks to your code and updates, can you implement mask generation for the test suite (new data) ？

**Comment by wooseok-shin** [comment]
I have added inference.py and inference.sh files to reflect your suggestion.
And I have updated README, please see [this section](https://github.com/wooseok-shin/PrevMatch?tab=readme-ov-file#inference-on-custom-dataset).
